add_newline = true
format = """
$directory\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$cmd_duration
$character
"""

[character]
success_symbol = "[](bold green)"
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 99
truncate_to_repo = false

[git_status]
staged = '++\($count\)'
ahead = "↑"
behind = "↓"
modified = "±"

